compute_environment: LOCAL_MACHINE
debug: true
deepspeed_config:
  deepspeed_config_file: /NAS6/Members/linchenxi/morocco/config/config_deepspeed.json
  deepspeed_multinode_launcher: standard
  zero3_init_flag: true
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_process_ip: 172.20.2.186
main_process_port: 4833
main_training_function: main
num_machines: 2
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
