PROJECT:
  task: "finetune" # either "finetune" or "pretrain" 
  pretrain: "dinov2"
  downstream: null # if task == "finetune", please specify the downstream task
  model_idx: "8"
  # description: "continue pretraining with satlas multiple classes"
  description: "finetune with Sen1Flood data "
PATH:
  # data_dir: "/NAS6/Members/linchenxi/projects/RS_foundation_model/flood_prediction"
  data_dir: "/NAS3/Members/linchenxi/projects/foundation_model/flood_prediction"
  log_outdir: "/NAS3/Members/linchenxi/projects/foundation_model/logs"
  model_outdir: "/NAS3/Members/linchenxi/projects/foundation_model/model"
MODEL:
  class_of_interest:
    pretrain_class:
      - water
      - developed
      - 
        - tree
        - shrub
        - grass
      - crop
    pretrain_class_weight: []
    finetune_class:
      - water
    finetune_class_weight:
      - 0.1
      - 0.5
  optimization:
    customized_weight: true
    img_size: 512
    batch_size: 8
    num_epoch: 500
    optimizer: "AdamW"
    scheduler: null
    weight_decay: 0
    momentum: 0.9
    base_lr: 1e-4
    total_steps_ratio: 0.2
    warmup_steps_ratio: 0.01
    num_train_samples: 5000
    num_vali_samples: 1000
  architecture:
    freeze_backbone: true
    use_projection: true
    projection_dim_ratio: 0.5 # reduce the hidden space feature dimension by this ratio
    num_layers: 2
    use_init: true
    use_bn: true
    hidden_dim: 2048
    bottleneck_dim: 256  
PRETRAIN:
  cfg_dino: "/NAS3/Members/linchenxi/projects/DINOV2/model3/config.yaml"
  cfg_satlas: "/NAS3/Members/linchenxi/projects/foundation_model/model/pretrain_dinov2_12/config.yaml"
  weights_dino_pretrain: "/NAS3/Members/linchenxi/projects/DINOV2/model3/eval/training_12499/teacher_checkpoint.pth"
  weights_satlas_pretrain: "/NAS3/Members/linchenxi/projects/foundation_model/model/pretrain_dinov2_12/best"
  statistics_satlas:
    mean:
      - 91.392
      - 79.3305
      - 67.677
      - 65.739
      - 84.1245
      - 93.1515
      - 90.4485
      - 75.6075
      - 57.783
    standard_deviation:
      - 16.32
      - 18.36
      - 2.4225
      - 12.24
      - 17.085
      - 20.4
      - 21.675
      - 18.87
      - 15.3 
  statistics_sen1flood:
    mean:
      - 1189.2240032217355
      - 1335.7876259041898
      - 1369.555378215939
      - 1432.4846319273197
      - 2329.1874191028446
      - 2776.599471278697
      - 2559.5920587145415
      - 1986.2344462964788
      - 1150.1873175658327
    standard_deviation:
      - 504.48473658532214
      - 409.57012279339966
      - 395.4498976071994
      - 459.6583462832101
      - 640.6401557563074
      - 771.8186296160205
      - 743.4712046089181
      - 695.772232693198
      - 522.1633726674359
  statistics_sen12ms:
    mean_s1:
      - -11.415
      - -19.191
    standard_deviation_s1:
      - 4.5995106261427425
      - 6.295987531753855
    mean_s2:
      - 3036.4113700000003
      - 2842.2263000000003
      - 2683.16342
      - 2866.1911400000004
      - 3013.40663
      - 3429.34514
      - 3683.54561
      - 3555.69409
      - 3840.27188
      - 1689.06212
      - 311.54035000000005
      - 2732.52887
      - 2098.23427
    standard_deviation_s2:
      - 23.232755303665556
      - 23.497584322649
      - 22.0600702854728
      - 23.78249473877793
      - 23.284778482948898
      - 22.055317907479818
      - 22.17036010081929
      - 21.445922642777578
      - 21.999025478416083
      - 15.513665105319244
      - 6.944271812076483
      - 13.64875287343133
      - 11.590661974192846

