PATH:
  data_dir: "/NAS6/Members/linchenxi/projects/RS_foundation_model/satlas"
  log_outdir: "/NAS6/Members/linchenxi/projects/RS_foundation_model/logs"
  model_outdir: "/NAS6/Members/linchenxi/projects/RS_foundation_model/model"
MODEL:
  class_of_interest:
    - water
    - developed
    - 
      - tree
      - shrub
      - grass
    - crop
  customized_weight: true
  img_size: 512
  batch_size: 8
  num_epoch: 500
  optimizer: "AdamW"
DINO:
  cfg_dino: "/NAS6/Members/linchenxi/projects/DINOV2/model3/config.yaml"
  weight_dino: "/NAS6/Members/linchenxi/projects/DINOV2/model3/eval/training_12499/teacher_checkpoint.pth"

