PROJECT:
  task: "object detection"
  model_idx: "1"
  description: "A DETR model"
PATH:
  # data_dir: "/NAS6/Members/linchenxi/projects/RS_foundation_model/flood_prediction"
  data_dir: "/NAS3/Members/linchenxi/projects/datasets"
  log_outdir: "/NAS3/Members/linchenxi/projects/object_detection/detr/logs"
  model_outdir: "/NAS3/Members/linchenxi/projects/object_detection/detr/model"
MODEL:
  optimization:
    batch_size: 8
    num_epoch: 500
    optimizer: "AdamW"
    scheduler: null
    weight_decay: 1e-1
    momentum: 0.9
    base_lr: 5e-5
    total_steps_ratio: 0.2
    warmup_steps_ratio: 0.01
    num_train_samples: 5000
    num_vali_samples: 1000
  backbone:
    backbone: "resnet50"
    dilation: true
    position_embedding: "sine" # either "sine" or "learned"
  transformer:
    enc_layers: 6
    dec_layers: 6
    dim_feedforward: 2048
    hidden_dim: 256
    dropout: 0.1
    nheads: 8
    num_queries: 100
    pre_norm: true



